name:  Continuous Deployment

on:
  push:
    branches: [ develop ]

  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}/package'
      TargetFramework: net48

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True src

    - name: Test
      run: | 
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True tests
        dotnet test ${{ github.workspace }}/tests/bin/Release/${{ env.TargetFramework }}/Unity.Abstractions.Tests.dll

    - name: Publish
      run: |
        dotnet nuget push '${{ github.workspace }}/package/*' --source "https://nuget.pkg.github.com/unitycontainer/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
